global:
  scrape_interval: 5s

scrape_configs:

  # ========= CLOUD NODE =========
  - job_name: 'telegraf'
    static_configs:
      - targets: ['10.0.0.3:9273']   # telegraf on cloud-node

  - job_name: 'subscriber'
    static_configs:
      - targets: ['10.0.0.3:8000']   # subscriber metrics

  - job_name: 'cloud_node_exporter'
    static_configs:
      - targets: ['10.0.0.3:9100']   # cloud-node internal IP


  # ========= MQTT NODE =========
  - job_name: 'mqtt_telegraf'
    static_configs:
      - targets: ['10.0.0.4:9273']    # MQTT node telegraf metrics

  # ========= DEVICE NODE =========
  - job_name: 'devices_telegraf'
    static_configs:
      - targets: ['10.0.0.2:9273']    # Devices node telegraf metrics

  # ========= NODE EXPORTER (DISABLED) =========
  # You don’t have node exporter yet — uncomment later if installed.
  #
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets:
  #         - '172.31.35.174:9100'   # cloud-node
  #         - '172.31.39.30:9100'   # mqtt-node
  #         - '172.31.38.156:9100'  # devices-node
  #         - '172.31.42.61:9100'   # monitoring-node
