apiVersion: 1
datasources:
  - name: InfluxDB
    uid: influxdb
    type: influxdb
    access: proxy
    url: "http://10.0.0.3:8086"
    isDefault: true
    jsonData:
      httpMode: POST
      organization: "secure_iot"
      version: Flux
      defaultBucket: "iot_data"
    secureJsonData:
      token: "local_token_123"

  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: false
